### ISSUE TITLE
TiCon Longswords aren't swords?

### ISSUE THREAD

**Issue by Zsashas** [coolAlias/ZeldaSwordSkills#51]
I've reported this to TiCon as well, but they seem to be ignoring it, and I wasn't sure which end would need to fix it anyway.

Tinkers' Construct Longswords do not count as swords for breaking jars or using skills. May be in part because they do not block, they charge instead. However, Rapiers cannot block either, and they work (last time I checked).

If it is fixable on your end, there are a few other things that could count as swords, or at least weapons, but I'll wait to suggest that.

**Comment by coolAlias** [comment]
This has been reported many times, and it's because there is no possible way without some sort of universal library for modded weapons that do not extend ItemSword (such as the TC weapons) to be detected as swords by other mods.

As far as I was aware, TC already implemented some of my API to allow their weapons to be used with skills. If that's not the case, there is nothing else I can do.

I'm considering allowing items to be registered as swords via inter-mod messages instead of by adding an interface; perhaps that will make it easier for other modders to adopt, or individuals like yourself to write a simple compatibility mod, but it will still require work for each and every mod that adds sword-like items that don't extend from ItemSword.

**Comment by coolAlias** [comment]
There - those commits should make it easier in the future for other modders / individuals to add compatibility. Something I've been meaning to do for a while now ;)
