### ISSUE TITLE
Shield Not Working

### ISSUE THREAD

**Issue by sonicdahedghog** [coolAlias/ZeldaSwordSkills#59]
The Shield doesn't block anymore, however, it still has the special positioning like It's on the side of your arm (In rec. version) but you can't block anymore.

**Comment by sonicdahedghog** [comment]
I used every version to test it - and BattleGear no longer acts like It's a shield.

**Comment by coolAlias** [comment]
You need to be more specific in which versions of each mod and Forge you are using, e.g.:
Forge 1.8-11.14.3.1464
ZSS 1.8-v3.2
BG2 1.8-v1.0.10.0

Using the above, shields work exactly as intended. Note that in order to be able to use shields while in the hotbar, you have to enable item use in the BG2 config, and the shields do not render while in 1st person when in the BG2 slots. Those are BG2 issues.

**Comment by sonicdahedghog** [comment]
Why am I so stupid.......
