### ISSUE TITLE
Will this ever get ported?

### ISSUE THREAD

**Issue by ToadsworthLP** [coolAlias/ZeldaSwordSkills#75]
As a mod dev myself I know everyone hates this question, but I'm not asking _when_, just if it's gonna happen _at all_. Most mods already are on 1.10.2 or even further, and I would be so happy to see this mod in modern Minecraft!

**Comment by coolAlias** [comment]
Please only post issues directly related to the functionality of the mod or its compatibility with another specific mod, preferably noting the specific version of the mod your issue is related to, e.g. 1.7.10-2.4.

Any inquiry related to when or whether the mod will update to some newer version of Minecraft and/or Forge will be closed and locked without further comment.

All other inquiries should be submitted in the [project thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293190-zelda-sword-skills-1-8-9-v3-4-and-1-7-10-v2-5-1-03).
